In [23]:
from sklearn import svm,datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
#dataset = datasets.fetch_olivetti_faces()
dataset = pd.read_csv('datald2.csv')
#dataset
#ds = dataset.to_numpy()
ds = pd.read_csv('a1dataset.csv')
ds

,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,...,x64,y64,x65,y65,x66,y66,x67,y67,x68,y68
0,43,41,42,51,43,61,45,71,49,81,...,82,77,92,78,82,77,77,78,73,77
1,42,42,41,52,43,63,45,74,47,83,...,82,77,92,79,82,77,78,78,73,78
2,44,40,43,50,45,61,47,72,49,82,...,82,77,91,78,82,77,78,78,74,77
3,42,41,42,51,43,62,45,73,48,83,...,82,77,91,79,82,77,77,78,73,78
4,43,40,42,50,44,61,46,72,48,82,...,82,77,91,79,82,77,77,78,73,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,46,43,45,50,44,57,45,64,47,71,...,62,74,73,75,63,78,59,78,56,77
2475,46,45,45,51,45,58,47,65,49,72,...,62,74,72,76,63,77,59,77,56,76
2476,48,45,46,50,46,57,48,63,49,70,...,63,74,72,75,63,76,59,76,56,75
2477,49,45,48,51,48,57,49,64,51,70,...,64,72,74,73,65,74,61,74,59,73
2478,51,45,50,51,50,57,51,63,53,70,...,65,73,74,74,66,75,63,74,60,73

In [24]:
dataset

,x1,y1,x2,y2,x3,y3,x4,y4,x5,y5,...,y64,x65,y65,x66,y66,x67,y67,x68,y68,is_Truth
0,43,41,42,51,43,61,45,71,49,81,...,77,92,78,82,77,77,78,73,77,1
1,42,42,41,52,43,63,45,74,47,83,...,77,92,79,82,77,78,78,73,78,1
2,44,40,43,50,45,61,47,72,49,82,...,77,91,78,82,77,78,78,74,77,1
3,42,41,42,51,43,62,45,73,48,83,...,77,91,79,82,77,77,78,73,78,1
4,43,40,42,50,44,61,46,72,48,82,...,77,91,79,82,77,77,78,73,77,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,46,43,45,50,44,57,45,64,47,71,...,74,73,75,63,78,59,78,56,77,0
2475,46,45,45,51,45,58,47,65,49,72,...,74,72,76,63,77,59,77,56,76,0
2476,48,45,46,50,46,57,48,63,49,70,...,74,72,75,63,76,59,76,56,75,0
2477,49,45,48,51,48,57,49,64,51,70,...,72,74,73,65,74,61,74,59,73,0
2478,51,45,50,51,50,57,51,63,53,70,...,73,74,74,66,75,63,74,60,73,0

In [25]:
X_train, X_test, y_train, y_test = train_test_split(ds, dataset.is_Truth, test_size=0.3,random_state=512)

In [26]:
clf = svm.SVC(kernel='poly')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [27]:
print("accuracy: ",metrics.accuracy_score(y_test, y_pred)*100,"%")
print("precision:",metrics.precision_score(y_test, y_pred)*100,"%")
print("recall:",metrics.recall_score(y_test, y_pred)*100,"%")

accuracy:  100.0 %
precision: 100.0 %
recall: 100.0 %

In [47]:

air = ds.values
tester = air[:,0:136]
y_pred_test = clf.predict(tester)
y_pred_test

/Users/kousthubhveturi/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([1, 1, 1, ..., 0, 0, 0])